
AWS_ACCESS_KEY_ID_ENV_KEY = "AWS_ACCESS_KEY_ID"
AWS_SECRET_ACCESS_KEY_ENV_KEY = "AWS_SECRET_ACCESS_KEY"
MONGO_DB_URL_ENV_KEY = "MONGO_DB_URL"

AWS_ACCESS_KEY_ID = "AKIAU2DDTLLTUH6SCEV4"
AWS_SECRET_ACCESS_KEY = "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"
MONGO_DB_URL = "mongodb+srv://iNeuron:RsPGmJUa69n558n@ineuron-ai-projects.7eh1w4s.mongodb.net/?retryWrites=true&w=majority"